<?php
/**
 * @file
 * Code for the CU Class Views feature.
 */

include_once 'cu_class_views.features.inc';

function cu_class_views_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-cu-classes-page') {
    // Subject
    $form['field_class_subject_value']['#type'] = 'select';
    $form['field_class_subject_value']['#options'] = cu_class_subject_values();
    unset($form['field_class_subject_value']['#size']);
    $form['field_class_subject_value']['#multiple'] = FALSE;
    $form['field_class_subject_value']['#empty_value'] = '';

    // Core Requirements
    $form['field_class_crse_attr_value_value']['#type'] = 'select';
    $form['field_class_crse_attr_value_value']['#options'] = cu_class_core_requirements_values();
    unset($form['field_class_crse_attr_value_value']['#size']);
    $form['field_class_crse_attr_value_value']['#multiple'] = FALSE;
    $form['field_class_crse_attr_value_value']['#empty_value'] = '';

    // Format
    $form['field_class_instruction_mode_value']['#type'] = 'select';
    $form['field_class_instruction_mode_value']['#options'] = cu_class_format_values();
    unset($form['field_class_instruction_mode_value']['#size']);
    $form['field_class_instruction_mode_value']['#multiple'] = FALSE;
    $form['field_class_instruction_mode_value']['#empty_value'] = '';

    // Session
    $form['field_class_session_code_value']['#type'] = 'select';
    $form['field_class_session_code_value']['#options'] = cu_class_session_values();
    unset($form['field_class_session_code_value']['#size']);
    $form['field_class_session_code_value']['#multiple'] = FALSE;
    $form['field_class_session_code_value']['#empty_value'] = '';

    $form['submit']['#attributes']['class'][] = 'button button-blue';
    $form['reset']['#attributes']['class'][] = 'button button-gray';
  }
}

function cu_class_views_views_pre_render(&$view) {
  $view_headers = '<div class="class-view-column-headers">
    <div class="row clearfix">
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        Class
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        Session
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
        Credits
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        Format
      </div>
    </div>
  </div>';
  $view->attachment_before = $view_headers;
}
